package ast.errors;

public enum SemanticErrorType {
	FUNCTIONNOTEXISTS,
	LOCALVARIABLEDOESNTEXIST,
	VARIABLEDOESNTEXIST,
	VARIABLENOTVAR,
	PARAMETERSMISMATCH,
	PASSEDREFERENCENOTVAR,
	BEHAVIOURERROR,
	DIFFERENTVARTYPE
}
