package ast.errors;

public enum SemanticErrorType {
	FUNCTIONNOTEXISTS,
	IDALREADYEXISTS,
	LOCALVARIABLEDOESNTEXIST,
	VARIABLEDOESNTEXIST,
	VARIABLENOTVAR,
	PARAMETERSMISMATCH,
	PASSEDREFERENCENOTVAR
}
